### ISSUE TITLE
Rename repository to something more suitable

### ISSUE THREAD

**Issue by JanMikes** [odbavto/presenter-route#1]
What about `presenter-route` -> `presenter-router` ?

@tomasvotruba, @koyuch any other ideas?

**Comment by TomasVotruba** [comment]
Presenter route suits the best to me.

**Comment by JanMikes** [comment]
There is inconsistency between repository name and composer package name
`odbavto/presenter-route` vs `odbav-to/presenter-route`, for this reason i will rename organisation.

**Comment by TomasVotruba** [comment]
@Lexinek Good call!
